import { Metadata } from 'next'
import { EquipmentROICalculator } from '@/components/calculators/EquipmentROICalculator'
import { BreadcrumbStructuredData, FAQStructuredData, HowToStructuredData, QAPageStructuredData } from '@/components/seo/StructuredData'

export const metadata: Metadata = {
  title: 'Equipment ROI Calculator - Return on Investment Calculator | EquipmentCalculators.com',
  description: 'Calculate equipment ROI, payback period, and revenue projections. Free equipment return on investment calculator with break-even analysis and profit projections.',
  keywords: 'equipment ROI calculator, return on investment calculator, payback period calculator, equipment profitability, business ROI analysis',
  openGraph: {
    title: 'Equipment ROI Calculator - Return on Investment Calculator',
    description: 'Calculate equipment ROI, payback period, and revenue projections with detailed break-even analysis.',
    type: 'website',
    url: 'https://equipmentcalculators.com/calculators/equipment-roi',
    images: [
      {
        url: 'https://equipmentcalculators.com/api/og?title=Equipment%20ROI%20Calculator&subtitle=ROI%2C%20Payback%2C%20Break-even',
        width: 1200,
        height: 630
      }
    ]
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Equipment ROI Calculator - Return on Investment Calculator',
    description: 'Calculate equipment ROI and payback period with detailed financial projections.',
    images: ['https://equipmentcalculators.com/api/og?title=Equipment%20ROI%20Calculator&subtitle=ROI%2C%20Payback%2C%20Break-even']
  }
}

export default function EquipmentROIPage() {
  const faqs = [
    { question: 'What is a good ROI?', answer: 'Varies by industry. 15%+ often considered excellent; 10–15% good; 5–10% acceptable for low risk.' },
    { question: 'How do I estimate revenue?', answer: 'Use conservative utilization and pricing assumptions. Include direct revenue and cost savings.' }
  ]

  return (
    <div className="container mx-auto px-4 py-8 max-w-7xl">
      <BreadcrumbStructuredData items={[
        { name: 'Home', url: 'https://equipmentcalculators.com' },
        { name: 'Calculators', url: 'https://equipmentcalculators.com/#calculators' },
        { name: 'Equipment ROI Calculator', url: 'https://equipmentcalculators.com/calculators/equipment-roi' }
      ]} />
      <FAQStructuredData faqs={faqs} />
      <QAPageStructuredData qa={[
        { question: 'What is a good equipment ROI?', answer: '15%+ is often considered excellent; 10–15% good; 5–10% acceptable for lower-risk equipment, but targets vary by industry.' },
        { question: 'Should I include tax benefits in ROI?', answer: 'Calculate operational ROI first, then add a tax-adjusted view including Section 179 and depreciation for a full picture.' },
        { question: 'How do I forecast utilization?', answer: 'Use conservative assumptions based on historical demand, hours of operation, and realistic ramp-up time.' }
      ]} />
      <HowToStructuredData
        name="How to use the Equipment ROI Calculator"
        steps={[
          { name: 'Enter equipment cost', text: 'The upfront purchase price.' },
          { name: 'Enter monthly revenue and expenses', text: 'Revenue generated by the equipment and ongoing operating costs.' },
          { name: 'Set analysis period', text: 'Choose 12–120 months to project performance.' },
          { name: 'Review ROI, payback, break-even', text: 'See ROI percentage, payback time, and break-even month.' }
        ]}
      />
      {/* Hero Section */}
      <div className="text-center mb-8">
        <h1 className="text-4xl md:text-5xl font-bold mb-4">
          Equipment ROI Calculator
        </h1>
        <p className="text-xl text-muted-foreground max-w-3xl mx-auto mb-6">
          Calculate return on investment, payback period, and revenue projections for equipment purchases. 
          See when your equipment will break even and start generating profit.
        </p>
        <div className="flex flex-wrap justify-center gap-4 text-sm text-muted-foreground">
          <span>✓ ROI calculations</span>
          <span>✓ Payback period</span>
          <span>✓ Break-even analysis</span>
          <span>✓ Monthly projections</span>
        </div>
      </div>

      {/* Calculator */}
      <EquipmentROICalculator className="mb-12" />

      {/* Understanding ROI */}
      <div className="max-w-4xl mx-auto space-y-8">
        <div className="text-center">
          <h2 className="text-3xl font-bold mb-4">Understanding Equipment ROI</h2>
          <p className="text-muted-foreground">
            Equipment ROI measures how effectively your equipment investment generates profit over time.
          </p>
        </div>

        <div className="grid md:grid-cols-2 gap-8">
          <div className="space-y-4">
            <h3 className="text-xl font-semibold">Key ROI Metrics</h3>
            <ul className="space-y-2 text-muted-foreground">
              <li>• <strong>ROI Percentage:</strong> Total return as percentage of initial investment</li>
              <li>• <strong><a href="/glossary#payback-period" className="underline">Payback Period</a>:</strong> Time to recover initial equipment cost</li>
              <li>• <strong><a href="/glossary#break-even" className="underline">Break-Even Point</a>:</strong> When cumulative profit equals investment</li>
              <li>• <strong>Net Profit:</strong> Total profit after all costs over analysis period</li>
            </ul>
          </div>

          <div className="space-y-4">
            <h3 className="text-xl font-semibold">Revenue Considerations</h3>
            <ul className="space-y-2 text-muted-foreground">
              <li>• <strong>Direct Revenue:</strong> Income directly generated by equipment</li>
              <li>• <strong>Productivity Gains:</strong> Increased efficiency and output</li>
              <li>• <strong>Cost Savings:</strong> Reduced labor or operational costs</li>
              <li>• <strong>Operating Expenses:</strong> Maintenance, fuel, insurance, labor</li>
            </ul>
          </div>
        </div>
      </div>

      {/* ROI Benchmarks */}
      <div className="max-w-4xl mx-auto mt-12 space-y-6">
        <h2 className="text-3xl font-bold text-center">ROI Benchmarks by Industry</h2>
        
        <div className="grid md:grid-cols-3 gap-6">
          <div className="text-center p-6 bg-green-50 rounded-lg border-2 border-green-200">
            <div className="text-2xl font-bold text-green-700 mb-2">20%+ ROI</div>
            <div className="font-semibold mb-1 text-green-600">Excellent</div>
            <div className="text-sm text-green-600">
              High-productivity equipment, direct revenue generation
            </div>
          </div>
          
          <div className="text-center p-6 bg-blue-50 rounded-lg border-2 border-blue-200">
            <div className="text-2xl font-bold text-blue-700 mb-2">10-20% ROI</div>
            <div className="font-semibold mb-1 text-blue-600">Good</div>
            <div className="text-sm text-blue-600">
              Standard business equipment, solid returns
            </div>
          </div>
          
          <div className="text-center p-6 bg-yellow-50 rounded-lg border-2 border-yellow-200">
            <div className="text-2xl font-bold text-yellow-700 mb-2">5-10% ROI</div>
            <div className="font-semibold mb-1 text-yellow-600">Moderate</div>
            <div className="text-sm text-yellow-600">
              Infrastructure equipment, long-term benefits
            </div>
          </div>
        </div>
      </div>

      {/* Industry Examples */}
      <div className="max-w-4xl mx-auto mt-12 space-y-6">
        <h2 className="text-3xl font-bold text-center">Industry-Specific Examples</h2>
        
        <div className="grid md:grid-cols-2 gap-8">
          <div className="space-y-6">
            <div className="p-6 border rounded-lg">
              <h3 className="text-lg font-semibold mb-3 text-orange-600">Construction Equipment</h3>
              <div className="space-y-2 text-sm">
                <div><strong>Revenue Sources:</strong> Job contracts, hourly rates, increased capacity</div>
                <div><strong>Typical ROI:</strong> 15-25% for actively used equipment</div>
                <div><strong>Payback:</strong> 2-4 years depending on utilization</div>
              </div>
            </div>
            
            <div className="p-6 border rounded-lg">
              <h3 className="text-lg font-semibold mb-3 text-blue-600">Medical Equipment</h3>
              <div className="space-y-2 text-sm">
                <div><strong>Revenue Sources:</strong> Patient procedures, diagnostic services</div>
                <div><strong>Typical ROI:</strong> 20-40% for high-utilization equipment</div>
                <div><strong>Payback:</strong> 1-3 years for specialized equipment</div>
              </div>
            </div>
          </div>
          
          <div className="space-y-6">
            <div className="p-6 border rounded-lg">
              <h3 className="text-lg font-semibold mb-3 text-green-600">Manufacturing Equipment</h3>
              <div className="space-y-2 text-sm">
                <div><strong>Revenue Sources:</strong> Increased production, quality improvements</div>
                <div><strong>Typical ROI:</strong> 12-20% for automation equipment</div>
                <div><strong>Payback:</strong> 3-5 years for major equipment</div>
              </div>
            </div>
            
            <div className="p-6 border rounded-lg">
              <h3 className="text-lg font-semibold mb-3 text-purple-600">Restaurant Equipment</h3>
              <div className="space-y-2 text-sm">
                <div><strong>Revenue Sources:</strong> Menu expansion, faster service, lower labor</div>
                <div><strong>Typical ROI:</strong> 15-30% for kitchen efficiency equipment</div>
                <div><strong>Payback:</strong> 1-2 years for high-impact equipment</div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Maximizing ROI Tips */}
      <div className="max-w-4xl mx-auto mt-12 space-y-6">
        <h2 className="text-3xl font-bold text-center">Maximizing Equipment ROI</h2>
        
        <div className="grid md:grid-cols-2 gap-8">
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-green-600">Best Practices</h3>
            <ul className="space-y-2 text-muted-foreground">
              <li>• Buy equipment when you have confirmed work/demand</li>
              <li>• Choose reliable brands with good resale value</li>
              <li>• Maximize equipment utilization rates</li>
              <li>• Implement preventive maintenance programs</li>
              <li>• Train operators for efficient usage</li>
              <li>• Consider financing to preserve working capital</li>
            </ul>
          </div>
          
          <div className="space-y-4">
            <h3 className="text-lg font-semibold text-red-600">Common Mistakes</h3>
            <ul className="space-y-2 text-muted-foreground">
              <li>• Buying equipment without confirmed revenue stream</li>
              <li>• Underestimating operating and maintenance costs</li>
              <li>• Ignoring equipment utilization rates</li>
              <li>• Buying oversized equipment for actual needs</li>
              <li>• Not factoring in equipment obsolescence</li>
              <li>• Focusing only on purchase price, not total cost</li>
            </ul>
          </div>
        </div>
      </div>

      {/* ROI Improvement Strategies */}
      <div className="max-w-4xl mx-auto mt-12 space-y-6">
        <h2 className="text-3xl font-bold text-center">ROI Improvement Strategies</h2>
        
        <div className="grid md:grid-cols-3 gap-6">
          <div className="text-center p-6 border rounded-lg">
            <h3 className="text-lg font-semibold mb-3">Increase Revenue</h3>
            <ul className="text-sm text-muted-foreground space-y-1">
              <li>• Higher utilization rates</li>
              <li>• Premium service pricing</li>
              <li>• New service offerings</li>
              <li>• Faster project completion</li>
            </ul>
          </div>
          
          <div className="text-center p-6 border rounded-lg">
            <h3 className="text-lg font-semibold mb-3">Reduce Costs</h3>
            <ul className="text-sm text-muted-foreground space-y-1">
              <li>• Preventive maintenance</li>
              <li>• Efficient operations</li>
              <li>• Bulk purchasing</li>
              <li>• Energy-efficient equipment</li>
            </ul>
          </div>
          
          <div className="text-center p-6 border rounded-lg">
            <h3 className="text-lg font-semibold mb-3">Optimize Financing</h3>
            <ul className="text-sm text-muted-foreground space-y-1">
              <li>• Compare financing options</li>
              <li>• Tax benefit optimization</li>
              <li>• Preserve working capital</li>
              <li>• Consider lease vs buy</li>
            </ul>
          </div>
        </div>
      </div>

      {/* FAQ Section */}
      <div className="max-w-4xl mx-auto mt-12 space-y-6">
        <h2 className="text-3xl font-bold text-center">Frequently Asked Questions</h2>
        
        <div className="space-y-4">
          <details className="border rounded-lg p-4">
            <summary className="font-semibold cursor-pointer">What&apos;s a good ROI for equipment purchases?</summary>
            <p className="text-muted-foreground mt-2">
              A good ROI depends on your industry and risk tolerance. Generally, 15%+ is considered excellent, 
              10-15% is good, and 5-10% is acceptable for low-risk equipment. Equipment that generates direct 
              revenue should target higher ROIs than support equipment.
            </p>
          </details>
          
          <details className="border rounded-lg p-4">
            <summary className="font-semibold cursor-pointer">How do I calculate revenue generated by equipment?</summary>
            <p className="text-muted-foreground mt-2">
              Include all revenue directly attributable to the equipment: increased sales, new services offered, 
              higher productivity, labor cost savings, and efficiency improvements. Be conservative in estimates 
              and factor in realistic utilization rates.
            </p>
          </details>
          
          <details className="border rounded-lg p-4">
            <summary className="font-semibold cursor-pointer">Should I include tax benefits in ROI calculations?</summary>
            <p className="text-muted-foreground mt-2">
              Yes, but separately from operational ROI. Tax benefits like Section 179 deductions, bonus depreciation, 
              and regular depreciation provide real value. Calculate both operational ROI and tax-adjusted ROI for 
              a complete picture.
            </p>
          </details>
          
          <details className="border rounded-lg p-4">
            <summary className="font-semibold cursor-pointer">How often should I recalculate equipment ROI?</summary>
            <p className="text-muted-foreground mt-2">
              Review ROI annually or when business conditions change significantly. Track actual vs. projected 
              performance to improve future equipment investment decisions. Some businesses review quarterly 
              for critical equipment.
            </p>
          </details>
        </div>
      </div>

      {/* In-Depth Guide */}
      <div className="max-w-4xl mx-auto mt-16 space-y-8">
        <h2 className="text-3xl font-bold text-center">In-Depth Guide: Equipment ROI</h2>
        <p className="text-muted-foreground text-lg text-center">
          Go beyond simple payback and model the full business impact of your equipment investment.
        </p>
        <div className="space-y-6">
          <section>
            <h3 className="text-xl font-semibold mb-2">Inputs That Matter</h3>
            <ul className="list-disc pl-6 text-muted-foreground space-y-1">
              <li>Realistic utilization and pricing assumptions</li>
              <li>Maintenance, consumables, and labor costs</li>
              <li>Downtime and learning curve impacts</li>
            </ul>
          </section>
          <section>
            <h3 className="text-xl font-semibold mb-2">Improving ROI</h3>
            <ul className="list-disc pl-6 text-muted-foreground space-y-1">
              <li>Increase utilization with scheduling and cross-training</li>
              <li>Reduce costs with preventive maintenance</li>
              <li>Bundle financing to preserve cash and accelerate deployment</li>
            </ul>
          </section>
          <section>
            <h3 className="text-xl font-semibold mb-2">When to Recalculate</h3>
            <ul className="list-disc pl-6 text-muted-foreground space-y-1">
              <li>Quarterly for high-impact equipment</li>
              <li>When pricing, throughput, or cost structure changes</li>
              <li>Before refinancing or major upgrades</li>
            </ul>
          </section>
        </div>
      </div>

      {/* Related Calculators & Resources */}
      <div className="max-w-4xl mx-auto mt-16 space-y-6">
        <h2 className="text-3xl font-bold text-center">Related Calculators & Resources</h2>
        <div className="grid md:grid-cols-2 gap-4">
          <div className="p-4 border rounded-lg">
            <h3 className="font-semibold mb-2">Compare or Explore</h3>
            <ul className="space-y-1 text-blue-600">
              <li><a className="hover:underline" href="/calculators/equipment-loan">Equipment Loan Calculator</a></li>
              <li><a className="hover:underline" href="/calculators/equipment-lease">Equipment Lease Calculator</a></li>
              <li><a className="hover:underline" href="/calculators/lease-vs-buy">Lease vs Buy Calculator</a></li>
            </ul>
          </div>
          <div className="p-4 border rounded-lg">
            <h3 className="font-semibold mb-2">Industry Pages</h3>
            <ul className="space-y-1 text-blue-600">
              <li><a className="hover:underline" href="/calculators/construction">Construction Equipment</a></li>
              <li><a className="hover:underline" href="/calculators/medical">Medical Equipment</a></li>
              <li><a className="hover:underline" href="/calculators/restaurant">Restaurant Equipment</a></li>
              <li><a className="hover:underline" href="/calculators/manufacturing">Manufacturing Equipment</a></li>
            </ul>
          </div>
        </div>
        <div className="text-center text-sm text-muted-foreground">
          See definitions in the <a className="underline" href="/glossary">Equipment Financing Glossary</a>.
        </div>
      </div>
    </div>
  )
}